# Generated by Django 3.1 on 2020-08-16 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0003_auto_20200816_1329'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='Season',
        ),
    ]
