# Generated by Django 3.1 on 2020-08-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0006_auto_20200817_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='name', max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='products/', verbose_name='Obrazek'),
        ),
    ]
