# Generated by Django 3.1 on 2020-08-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0007_auto_20200818_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=64),
        ),
        migrations.AlterField(
            model_name='employee',
            name='img',
            field=models.ImageField(upload_to='team'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='products', verbose_name='Obrazek'),
        ),
    ]
