# Generated by Django 3.1 on 2020-08-21 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0011_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
