# Generated by Django 3.1 on 2020-08-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0014_auto_20200825_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='img',
            field=models.ImageField(null=True, upload_to='team', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(null=True, upload_to='products', verbose_name='Obrazek'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='season',
            name='img',
            field=models.ImageField(null=True, upload_to='season', verbose_name='Obrazek'),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(default='', max_length=64, unique=True, verbose_name='Nazwa'),
        ),
    ]
