# Generated by Django 3.1 on 2020-08-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0016_auto_20200826_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nazwa'),
        ),
    ]
