# Generated by Django 3.1 on 2020-08-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0017_auto_20200826_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=64)),
                ('slug', models.SlugField(default='', max_length=64)),
                ('img', models.ImageField(null=True, upload_to='company', verbose_name='Obrazek')),
            ],
        ),
    ]
