# Generated by Django 3.1 on 2020-09-03 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sklep.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sklep', '0019_auto_20200826_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='img',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=128, null=True, verbose_name='Przypis'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(max_length=128, null=True, verbose_name='Krótki opis'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='occupation',
            field=models.CharField(max_length=64, null=True, verbose_name='Stanowisko'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Wybiesz konto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(validators=[sklep.models.minus_number_validate], verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='product',
            name='small_description',
            field=models.CharField(max_length=64, null=True, verbose_name='Przypis'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(null=True, validators=[sklep.models.stock_validate], verbose_name='Ilość'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat',
            field=models.FloatField(null=True, validators=[sklep.models.minus_number_validate], verbose_name='Vat'),
        ),
        migrations.AlterField(
            model_name='season',
            name='description',
            field=models.TextField(default='', null=True, verbose_name='Opis'),
        ),
    ]
