# Generated by Django 3.1 on 2020-09-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0020_auto_20200903_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='img',
            field=models.ImageField(null=True, upload_to='season', verbose_name='Obrazek'),
        ),
    ]
